services:
  db:
    build: ./db
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=pharmalivery_db
        #SERVER
      #- MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
        #LOCAL - DOCKER
      - MYSQL_ROOT_PASSWORD=12345
    expose:
      - 3306
      - 33060

  backend:
    command: gunicorn --bind 0.0.0.0:8000 --worker-class gthread "app:create_app()"
    build: ./backend
    restart: always
    volumes:
      - static:/app/app/static
    secrets:
      - db-password
    ports:
      - 8000:8000
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - static:/usr/share/nginx/html/static
    networks:
      - frontnet

volumes:
  db-data:
  static:

secrets:
  db-password:
    file: .db/password.txt

networks:
  backnet:
  frontnet:
